RECIPE_CATEGORY = "crafting-fluids"

CHUNK_SIZE = 32

--item name that electricity uses
ELECTRICITY_ITEM_NAME = "electricity"
ELECTRICITY_RATIO = 1000000 -- 1.000.000,  1 = 1MJ

MAX_FLUID_AMOUNT = 25000

ITERATIONS_TO_COLLECT_ELECTRICITY_REQUESTS = 4

TICKS_TO_COLLECT_REQUESTS = 40
TICKS_TO_FULFILL_REQUESTS = 20

TICKS_TO_COLLECT_GARBAGE = 60 * 60
